name: 'Install WordPress'

inputs:
  multisite:
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Start MySQL service
      shell: bash
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE db;' -uroot -proot
        mysql -e "CREATE USER 'db'@'localhost' IDENTIFIED BY 'db';" -uroot -proot
        mysql -e "GRANT ALL PRIVILEGES ON db.* TO 'db'@'localhost' WITH GRANT OPTION;" -uroot -proot

    - name: Launch web server
      shell: bash
      run: ./vendor/bin/wp server &

    - name: Setup .env
      shell: bash
      run: |
        cp .env.example .env
        sed -i 's/WP_HOME=.*/WP_HOME=http:\/\/localhost:8080/g' .env
        sed -i 's/DB_HOST=.*/DB_HOST=localhost/g' .env

    - name: Install WordPress
      if: ${{ inputs.multisite != 'true' }}
      shell: bash
      run: |
        ./vendor/bin/wp core install \
          --url=http://localhost:8080 \
          --title="Bedrock" \
          --admin_user="admin" \
          --admin_email="bedrock@example.test" \
          --skip-email

    - name: Install WordPress (multisite)
      if: ${{ inputs.multisite == 'true' }}
      shell: bash
      run: |
        ./vendor/bin/wp core multisite-install \
          --url=http://localhost:8080 \
          --title="Bedrock" \
          --admin_email="bedrock@example.test" \
          --skip-config \
          --skip-email
