---
# This file should be kept without site specific overrides, place them in
# vagrant.config.yml. That way when Drupal VM updates are brought in, this file
# can be overriden without manual inspection.

# Use DHCP assigned  IPs with vagrant-hostmanager
# Note: requires vagrant-vbguest to be disabled in Vagrantfile.local
vagrant_ip: dhcp
vagrant_plugins:
  - name: vagrant-hostmanager

# Needs to match with what we have in .env and vagrant_synced_folders.
drupal_core_path: "/var/www/wordpress/web"
drupal_domain: "{{ vagrant_hostname }}"
drupal_db_user: wordpress
drupal_db_password: wordpress
drupal_db_name: wordpress

# Disable Drupal specific features.
drupal_build_composer_project: false
drupal_composer_dependencies: []
drupal_install_site: false
configure_drush_aliases: false

apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
    </FilesMatch>
    SetEnv DEVELOPMENT true

ssl_certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
ssl_certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }} static.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
    certificate_file: "{{ ssl_certificate_file }}"
    certificate_key_file: "{{ ssl_certificate_key_file }}"

apache_vhosts_ssl: "{{ apache_vhosts }}"

apache_mods_enabled:
  - env.load
  - expires.load
  - headers.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load

php_version: "7.2"
nodejs_version: "12.x"

installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  # - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  - nodejs
  # - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  # - varnish
  - xdebug
  # - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - vim

composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }
  - { name: wp-cli/wp-cli-bundle, release: '^2.0.0' }

post_provision_tasks_dir:
  - "{{ config_dir }}/../vendor/generoi/genero-conf/post-provisioning/tasks/apache-env.yml"
  - "{{ config_dir }}/../vendor/generoi/genero-conf/post-provisioning/tasks/dotfiles.yml"
  - "{{ config_dir }}/../vendor/generoi/genero-conf/post-provisioning/tasks/wp-directories.yml"
  - "{{ config_dir }}/../vendor/generoi/genero-conf/post-provisioning/tasks/ssh-config.yml"
  - "{{ config_dir }}/provisioning/ssh-config.yml"
