---
# Site specific overrides.

vagrant_hostname: <example-project>.test
vagrant_machine_name: <example-project>

# If you want to use NFS instead (two-way sync) create a local.config.yml file
# where you override the vagrant_synced_folders variable with this value. This
# file is not tracked in git so the change would be for you alone.
#
# vagrant_synced_folders:
#   - local_path: .
#     destination: /var/www/wordpress
#     type: nfs
#     create: true
#
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/wordpress
    id: wordpress
    type: rsync
    create: true
    excluded_paths: ['.git/', '.tmp/', '/.build/', 'node_modules/', '/web/app/uploads/', '/web/app/cache/', '/web/app/acf-json/']
    options_override:
      rsync__chown: false
      rsync__verbose: true
      rsync__args: [
        "--verbose", "--archive", "--delete", "--copy-links",
        "--owner", "--group", "--usermap=*:vagrant", "--groupmap=*:www-data",
      ]
  - local_path: web/app/acf-json
    destination: /var/www/wordpress/web/app/acf-json
    type: nfs
    create: true
  - local_path: web/app/uploads
    destination: /var/www/wordpress/web/app/uploads
    type: nfs
    create: true

# If you need to use cron jobs.
# drupalvm_cron_jobs:
#   - name: 'WordPress Cron'
#     minute: '*/30'
#     job: "cd {{ drupal_core_path }} && wp cron event run --due-now --quiet 2>/dev/null"

# If you want to adjust this, create a local.config.yml file where you override
# the value. This file is not tracked in git.
vagrant_memory: 1024

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1
# php_version: "5.6"
php_xdebug_idekey: sublime.xdebug
# XDebug configuration. Disable for better performance.
php_xdebug_default_enable: 1
# @todo Until next Drupal VM release
php_xdebug_version: 2.6.0
