---
# Site specific overrides.

vagrant_hostname: <example-project>.test
vagrant_machine_name: <example-project>

# On windows this will automatically be changed to `vboxsf`
# @see Vagrantfile.local
vagrant_synced_folder_default_type: nfs
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/wordpress
    type: "{{ vagrant_synced_folder_default_type }}"
    create: true
    mount_options: ['nolock', 'noatime', 'actimeo=1']

# If you need to use cron jobs.
# drupalvm_cron_jobs:
#   - name: 'WordPress Cron'
#     minute: '*/30'
#     job: "cd {{ drupal_core_path }} && wp cron event run --due-now --quiet 2>/dev/null"

# If you want to adjust this, create a local.config.yml file where you override
# the value. This file is not tracked in git.
vagrant_memory: 1024

# See http://docs.drupalvm.com/en/latest/extras/xdebug/
php_xdebug_idekey: VSCODE

# XDebug configuration. Disable for better performance.
php_xdebug_default_enable: 1
php_xdebug_remote_autostart: "true"
