name: '__deploy'
on:
  workflow_call:
    inputs:
      log_level:
        required: true
        type: string
      environment:
        required:  true
        type: string

    secrets:
      KINSTA_DEPLOY_PRIVATE_KEY:
        required: true
      PACKAGIST_GITHUB_TOKEN:
        required: true
      NPM_FONTAWESOME_AUTH_TOKEN:
        required: true
jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.KINSTA_DEPLOY_PRIVATE_KEY }}

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          npm_fontawesome_auth_token: ${{ secrets.NPM_FONTAWESOME_AUTH_TOKEN }}
          packagist_github_token: ${{ secrets.PACKAGIST_GITHUB_TOKEN }}

      - name: Install development packages to run tests
        run: composer install:development

      - name: Run tests
        run: composer test --no-interaction

      - name: Add remote public keys to known hosts
        run: ssh-keyscan -p $(./vendor/bin/robo config env.@${{ inputs.environment }}.port || echo 22) $(./vendor/bin/robo config env.@${{ inputs.environment }}.host) >> ~/.ssh/known_hosts

      - name: Deploy
        run: ./vendor/bin/dep deploy ${{ inputs.environment }} ${{ inputs.log_level }}
