name: E2E tests
on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
jobs:
  e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set URL as environmnet variable so playwright uses it
        run: echo "URL=${{ inputs.url }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm e2e:install

      - name: Run E2E tests
        run: npm e2e:test

      - uses: actions/upload-artifact@v4
        with:
          name: Screenshot
          path: screenshot.jpg
