name: 'CI: E2E'
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url'
        default: 'https://gdsbedrock.kinsta.cloud'
  workflow_call:
    inputs:
      url:
        required: true
        type: string

permissions:
  contents: read

jobs:
  e2e:
    uses: generoi/github-actions/.github/workflows/e2e.yml@v2
    with:
      url: ${{ inputs.url }}
