name: Lighthouse report
on:
  workflow_call:
    inputs:
      urls:
        type: string
        default: https://gdsbedrock.kinsta.cloud/
  workflow_dispatch:
    inputs:
      urls:
        description: 'URL'
        default: https://gdsbedrock.kinsta.cloud/
env:
  AUDIT_DELAY: 60

jobs:
  lighthouse:
    name: Run lighthouse audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Warm up the caches
        run: curl -I -X GET '${{ inputs.urls }}' && sleep ${{ env.AUDIT_DELAY }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ inputs.urls }}
          uploadArtifacts: true
          temporaryPublicStorage: true

