name: Test
on:
  pull_request:

env:
  PROJECT_NAME: bedrock

jobs:
  test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (latest)
        uses: actions/checkout@v2
        if: github.event.inputs.ref == ''

      - name: Checkout Repository (specific reference)
        uses: actions/checkout@v2
        if: github.event.inputs.ref != ''
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup DDEV
        run: |
          sed -i 's/<example-project>/${{ env.PROJECT_NAME }}/g' .ddev/*

      - uses: jonaseberle/github-action-setup-ddev@v1

      - name: Configure basic http authentication for Composer
        run: ddev composer config --global http-basic.satispress.generodigital.com ${{ secrets.SATISPRESS_API_KEY }} ${{ secrets.SATISPRESS_PASSWORD }}

      - name: Install development packages to run tests
        run: ddev composer install:development

      - name: Run CI tests
        run: ddev composer ci --no-interaction

      - name: Build assets
        run: ddev composer build --no-interaction

      - name: Install WordPress
        run: ddev wp core install --url="http://${{ env.PROJECT_NAME }}.ddev.site" --title="${{ env.PROJECT_NAME }}" --admin_user="admin" --admin_password="admin" --admin_email="admin@example.test"

      - name: Load home page # @todo
        run: curl http://${{ env.PROJECT_NAME }}.ddev.site
