name: Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          npm_fontawesome_auth_token: ${{ secrets.NPM_FONTAWESOME_AUTH_TOKEN }}
          packagist_github_token: ${{ secrets.PACKAGIST_GITHUB_TOKEN }}

      - name: Install development packages to run tests
        run: composer install:development

      - name: Run CI tests
        run: composer ci --no-interaction

      - name: Install WordPress
        uses: ./.github/actions/install-wordpress
        with:
          multisite: 'false'

      - name: Optimize acorn
        run: ./vendor/bin/wp acorn optimize

      - name: Load frontpage and verify app.js script is loaded
        run: curl http://localhost:8080/ | grep '<script.*src=".*app/themes/gds/public/scripts/app.js'

      - name: Run unit tests
        run: composer phpunit
