name: "CI: Test"
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: generoi/github-actions/.github/workflows/test.yml@v2
    secrets:
      NPM_FONTAWESOME_AUTH_TOKEN: ${{ secrets.NPM_FONTAWESOME_AUTH_TOKEN }}
      COMPOSER_BOT_PRIVATE_KEY: ${{ secrets.COMPOSER_BOT_PRIVATE_KEY }}
    with:
      smoke_grep: 'app/themes/gds/public/scripts/app.js'
